### PR TITLE
Fix userinfo error forwarding

### LINKED ISSUE #37: Unsuccessful response from userinfo doesn't get forwarded properly
IAM replies with an InternalServerError while it should be Unauthorized

### PR DESCRIPTION
**Pull request by hygt**
Fixes #37

### CODE REVIEW

File: modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClient.scala [hunk 1]
```diff
@@ -51,18 +51,31 @@ class DownstreamAuthClient[F[_]](config: OidcConfig, cl: UntypedHttpClient[F], u
...
+    uicl(Get(config.userinfoEndpoint).addCredentials(OAuth2BearerToken(accessToken)))
+      .map(_.toUser(config.issuer))
       .recoverWith {
         case df: DecodingFailure =>
           log.error("Unable to decode UserInfo response", df)
-          F.raiseError(df)
+          F.raiseError(UnexpectedUnsuccessfulHttpResponse(HttpResponse(StatusCodes.BadGateway)))
         case UnexpectedUnsuccessfulHttpResponse(resp) =>
-          log.error("Received a failed response from the downstream oid provider for getting the UserInfo")
+          if (resp.status == StatusCodes.Unauthorized) {
```
Comment (wwajerowicz) [inline modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClient.scala]: Can we do pattern matching here instead of `if`, e.g. something along the lines of 
```
case UnexpectedUnsuccessfulHttpResponse(HttpResponse(StatusCodes.Unauthorized, _, _, ....) => (...)
case UnexpectedUnsuccessfulHttpResp(resp) => (....)
(..)
```

Comment (hygt) [reply modules/service/src/main/scala/ch/epfl/bluebrain/nexus/iam/service/auth/DownstreamAuthClient.scala]: I thought pattern matching would be unnecessarily clunky, that's why I used an `if`
